package com.example.Spring_Boot_Jpa_ER._04_1_to_1_bidir_spk_pkjc.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "purchasers")
public class Purchaser {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // The 'mappedBy' attribute is used to specify the referenced side
            // (non-owning side) of a relationship/association.
            mappedBy = "purchaser",
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child
            // entities.
            // That is, every time we manipulate the Purchaser entity, we also
            // manipulate the Habitation entity accordingly.
            cascade = CascadeType.ALL)
    private Habitation habitation;
}
