package com.example.Spring_Boot_Jpa_ER._09_1_to_N_bidir_fk_jc.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "articles")
public class Article {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "title")
    private String title;
    @Column(name = "content")
    private String content;
    // @OneToMany defines a one-to-many multiplicity association.
    @OneToMany(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete) should
            // cascade from the parent entity to the child entities.
            cascade = CascadeType.ALL,
            // fetch = FetchType.LAZY is optional option whether the association
            // should be fetched lazily or eagerly.
            fetch = FetchType.LAZY,
            // The 'mappedBy' attribute indicates that the entity is a back-reference
            // to the field that owns the relationship.
            mappedBy = "article")
    private List<Remark> remarks;
}
