package com.example.Spring_Boot_Jpa_ER._09_1_to_N_bidir_fk_jc.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "remarks")
public class Remark {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "consideration")
    private String consideration;
    // @ManyToOne defines a one-to-one association with another entity class,
    // which has a many-to-one multiplicity.
    // If the relationship is bidirectional, the non-owning side of the
    // OneToMany entity must use the 'mappedBy' element to specify the association
    // field or property of the entity, which owns the relationship.
    @ManyToOne(
            // fetch = FetchType.LAZY defines whether the association should be fetched
            // lazily or eagerly. It's optional.
            fetch = FetchType.LAZY)
    // @JoinColumn defines a column to join to an entity association
    // or item collection. It defines a foreign key column.
    @JoinColumn(
            // Foreign key column name.
            name = "article_id",
            // The name of the column referenced
            // by the foreign key column.
            referencedColumnName = "id"
    )
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Article article;
}
