package com.example.Spring_Boot_Jpa_ER._06_1_to_1_unidir_spk_mapsid.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "consumers")
public class Consumer {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child entities.
            // That is, every time we manipulate the Consumer entity, we also
            // manipulate the Domicile entity accordingly.
            cascade = CascadeType.ALL)
    // @MapsId simplifies One-to-One relationships by allowing two entities
    // to share a single primary key.
    // This helps implement the shared primary key strategy,
    // by telling Hibernate to map the primary key of a child entity
    // to the primary key of its related parent entity.
    // @OneToOne and @MapsId indicate that both the source and target entities
    // share the same primary key values.
    // The Domicile entity does not contain any references to Consumer,
    // since this is a one-way relationship (from Consumer to Domicile).
    @MapsId
    private Domicile domicile;
}
