package com.example.Spring_Boot_Jpa_ER._12_N_to_N_bidir_jt.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "courses")
public class Course {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "name")
    private String name;
    // @ManyToMany defines a many-to-many association
    // with a many-to-many multiplicity.
    @ManyToMany(
            // FetchType defines strategies for retrieving data from the database.
            fetch = FetchType.LAZY,
            // CascadeType defines a set of cascading operations that
            // are applied to the associated entity.
            // WARNING: Only cascade types PERSIST and MERGE are defined
            // for this entity. The REMOVE entity state transition does not make sense
            // for a @ManyToMany association, as it could trigger a chain deletion
            // that would eventually erase both sides of the association.
            // https://vladmihalcea.com/the-best-way-to-use-the-manytomany-annotation-with-jpa-and-hibernate/
            // https://vladmihalcea.com/a-beginners-guide-to-jpa-and-hibernate-cascade-types/
            cascade = {CascadeType.PERSIST, CascadeType.MERGE},
            // The 'mappedBy' attribute specifies the field that owns the relationship.
            mappedBy = "courses")
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    private Set<Student> students = new HashSet<>();
}
