package com.example.Spring_Boot_Jpa_ER._12_N_to_N_bidir_jt.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.*;
import lombok.*;

import java.util.HashSet;
import java.util.Set;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "students")
public class Student {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @ManyToMany defines a many-to-many association
    // with a many-to-many multiplicity.
    @ManyToMany(
            // FetchType defines strategies for retrieving data from the database.
            fetch = FetchType.LAZY,
            // CascadeType defines a set of cascading operations
            // that are applied to the associated entity.
            // WARNING: Only cascade types PERSIST and MERGE are defined for this entity.
            // The REMOVE entity state transition does not make sense for a @ManyToMany
            // association, as it could trigger a chain deletion that would eventually
            // erase both sides of the association.
            // https://vladmihalcea.com/the-best-way-to-use-the-manytomany-annotation-with-jpa-and-hibernate/
            // https://vladmihalcea.com/a-beginners-guide-to-jpa-and-hibernate-cascade-types/
            cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
            // Name of the join table.
            name = "student_course",
            joinColumns = @JoinColumn(
                    // Column of the 'student_course' table.
                    name = "student_id"
            ),
            inverseJoinColumns = @JoinColumn(
                    // Column of the 'student_course' table.
                    name = "course_id"
            )
    )
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    Set<Course> courses = new HashSet<>();

    // NOTE. The add/remove utility methods are mandatory,
    // for bidirectional associations, to ensure that both sides
    // of the association are synchronized.
    // https://vladmihalcea.com/the-best-way-to-use-the-manytomany-annotation-with-jpa-and-hibernate/
    // https://vladmihalcea.com/jpa-hibernate-synchronize-bidirectional-entity-associations/

    public void addCourse(Course course) {
        this.courses.add(course);
        course.getStudents().add(this);
    }

    public void removeCourse(long courseId) {
        Course course =
                this.courses.stream()
                        .filter(_course ->
                                _course.getId() == courseId)
                        .findFirst().orElse(null);
        if (course != null) {
            this.courses.remove(course);
            course.getStudents().remove(this);
        }
    }
}
