package com.example.Spring_Boot_Jpa_ER._02_1_to_1_bidir_fk_jc.entity;

import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "buyers")
public class Buyer {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator, which expects
    // values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child entities.
            // That is, every time you manipulate the Buyer entity, you also
            // manipulate the Address entity accordingly.
            cascade = CascadeType.ALL)
    // @JoinColumn is used on the association owner side
    // to specify the foreign key column name and other
    // attributes associated with the join column.
    @JoinColumn(name = "address_id")
    private Address address;
}

