package com.example.Spring_Boot_Jpa_ER._10_N_to_1_unidir_fk_jc.entity;

import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "opinions")
public class Opinion {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "consideration")
    private String consideration;
    // @ManyToOne defines a one-to-one association
    // with another entity class that has a multiplicity
    // of many-to-one.
    @ManyToOne
    // @JoinColumn is used on the association owner side
    // to specify the foreign key column name and other attributes
    // associated with the join column.
    @JoinColumn(name = "story_id")
    private Story story;
}
