package com.example.Spring_Boot_Jpa_ER._11_N_to_N_unidir_jt.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "employees")
public class Employee {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @ManyToMany defines a many-to-many association
    // with a many-to-many multiplicity.
    @ManyToMany(
            // FetchType defines strategies for retrieving data from the database.
            fetch = FetchType.LAZY,
            // CascadeType defines a set of cascading operations
            // that are applied to the associated entity.
            // WARNING: Only cascade types PERSIST and MERGE are defined
            // for this entity.
            // The REMOVE entity state transition does not make sense
            // for a @ManyToMany association, as it could trigger
            // a chain deletion that would eventually erase both
            // sides of the association.
            // https://vladmihalcea.com/the-best-way-to-use-the-manytomany-annotation-with-jpa-and-hibernate/
            // https://vladmihalcea.com/a-beginners-guide-to-jpa-and-hibernate-cascade-types/
            cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
            // Name of the join table
            name = "employee_project",
            joinColumns = @JoinColumn(
                    // Column of the employee_project table
                    name = "employee_id"
            ),
            inverseJoinColumns = @JoinColumn(
                    // Column of the employee_project table
                    name = "project_id"
            )
    )
    @JsonInclude(JsonInclude.Include.NON_NULL)
    List<Project> projects;

    // NOTE. The add/remove utility methods are mandatory,
    // for bidirectional associations, to ensure that
    // both sides of the association are synchronized.
    // https://vladmihalcea.com/the-best-way-to-use-the-manytomany-annotation-with-jpa-and-hibernate/
    // https://vladmihalcea.com/jpa-hibernate-synchronize-bidirectional-entity-associations/

    public void addProject(Project project) {
        this.projects.add(project);
    }

    public void removeProject(long projectId) {
        this.projects.stream()
                .filter(project ->
                        project.getId() == projectId)
                .findFirst()
                .ifPresent(project ->
                        this.projects.remove(project));
    }
}
