package com.example.Spring_Boot_Jpa_ER._08_1_to_N_unidir_fk_jc.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "posts")
public class Post {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "title")
    private String title;
    @Column(name = "content")
    private String content;
    // @OneToMany defines a multivalued association
    // with a multiplicity of one-to-many.
    @OneToMany(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // should cascade from the parent entity to the child
            // entities.
            cascade = CascadeType.ALL,
            // fetch = FetchType.LAZY defines whether the association
            // should be fetched lazily or eagerly. It's optional.
            fetch = FetchType.LAZY,
            // orphanRemoval = true helps to remove a child entity (Comment entry)
            // from the database, if we remove it from the parent collection
            // (List<Comment> comments). It's optional.
            orphanRemoval = true)
    // @JoinColumn is used on the association owner side
    // to specify the foreign key column name and other attributes
    // associated with the join column.
    @JoinColumn(name = "post_id")
    private List<Comment> comments;
}
