package com.example.Spring_Boot_Jpa_ER._07_1_to_1_bidir_spk_mapsid.entity;

import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "vendees")
public class Vendee {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // The 'mappedBy' attribute is used to specify the reference side
            // (non-owning side) of the relationship/association.
            mappedBy = "vendee",
            // CascadeType.ALL is a Hibernate cascade type that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child
            // entities.
            // That is, every time you manipulate the Vendee entity,
            // you also manipulate the Abode entity accordingly.
            cascade = CascadeType.ALL)
    private Abode abode;
}
