package com.example.Spring_Boot_Jpa_ER._03_1_to_1_unidir_spk_pkjc.entity;

import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "clients")
public class Client {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child entities.
            // That is, every time we manipulate the Client entity, we also
            // manipulate the Residence entity accordingly.
            cascade = CascadeType.ALL)
    // @PrimaryKeyJoinColumn defines a primary key column,
    // which is used as a foreign key to join another table.
    @PrimaryKeyJoinColumn
    private Residence residence;
}
