package com.example.Spring_Boot_Jpa_ER._05_1_to_1_jt.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "places")
public class Place {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "city")
    private String city;
    @Column(name = "street")
    private String street;
    @Column(name = "building")
    private String building;
    @Column(name = "apartment")
    private String apartment;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // The 'mappedBy' attribute is used to specify the reference side
            // (non-owning side) of a relationship/association.
            mappedBy = "place")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Shopper shopper;
}
