package com.example.Spring_Boot_Jpa_ER._05_1_to_1_jt.entity;

import jakarta.persistence.*;
import lombok.*;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Builder
@Entity(name = "shoppers")
public class Shopper {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // should cascade from the parent entity to the child
            // entities.
            cascade = CascadeType.ALL)
    // @JoinTable defines the details of the Join table between
    // the Shopper and Place entities.
    // Defines the name of the join table (shopper_place) and the names of the columns
    // of the foreign key in the join table (shopper_id and place_id).
    //
    // @JoinColumn marks a column as a join column for an entity or
    // collection of items association.
    // 'joinColumns' is used to reference the Shopper entity,
    // and 'inverseJoinColumns' refers to the Place entity.
    //
    // From the Shopper perspective, the 'id' column of the 'shoppers' table will have
    // a foreign key relationship with the 'shopper_id' column of the 'shopper_place' table.
    // The 'inverseJoinColumns(place_id)' attribute refers to the other side of Shopper,
    // which is the Place entity.
    @JoinTable(
            // Name of the join table.
            name = "shopper_place",
            // 'joinColumns' is used to reference the Shopper entity.
            joinColumns = {
                    @JoinColumn(
                            // Column of the 'shopper_place' table
                            name = "shopper_id",
                            // Column of the 'shoppers' table
                            referencedColumnName = "id"
                    )
            },
            // 'inverseJoinColumns' refers to the Place entity.
            inverseJoinColumns = {
                    @JoinColumn(
                            // Column of the 'shopper_place' table
                            name = "place_id",
                            // Column of the 'places' table
                            referencedColumnName = "id"
                    )
            }
    )
    private Place place;
}
