package com.example.Spring_Boot_Jpa_ER._01_1_to_1_unidir_fk_jc.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@NoArgsConstructor
@AllArgsConstructor
@Setter
@Getter
@Entity(name = "customers")
public class Customer {
    @Id
    // GenerationType.IDENTITY relies on IdentityGenerator,
    // which expects values generated by the identity column in the database.
    // These values are automatically incremented.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column(name = "email")
    private String email;
    // @OneToOne defines a one-to-one association with another entity,
    // which has a one-to-one multiplicity.
    @OneToOne(
            // CascadeType.ALL is a cascade type in Hibernate that specifies
            // that all state transitions (create, update, delete)
            // must cascade from the parent entity to the child entities.
            // That is, every time we manipulate the Customer entity, we also
            // manipulate the Location entity accordingly.
            cascade = CascadeType.ALL)
    // @JoinColumn specifies a column to join an entity association
    // or an item collection.
    // @JoinColumn is used to specify the name of the column
    // of the foreign key in the customers table that corresponds to
    // the primary key in the locations table.
    // @JoinColumn is used on the association owner side.
    @JoinColumn(name = "location_id", referencedColumnName = "id")
    private Location location;
}
